# Generated by Django 4.2 on 2024-01-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category', verbose_name='Категория'),
        ),
    ]
