# Generated by Django 4.2 on 2024-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='num_version',
            field=models.IntegerField(unique=True, verbose_name='Номер версии'),
        ),
    ]
