# Generated by Django 4.2 on 2024-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_name_alter_version_num_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='num_version',
            field=models.IntegerField(auto_created=True, unique=True, verbose_name='Номер версии'),
        ),
    ]
