# Generated by Django 4.2 on 2024-02-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_version_options_alter_version_num_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='sign',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('product', 'num_version')},
        ),
    ]
