# Generated by Django 4.2 on 2024-02-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_sign_alter_version_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num_version',
            field=models.IntegerField(auto_created=True, verbose_name='Номер версии'),
        ),
    ]
