# Generated by Django 4.2 on 2024-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_num_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='sign',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
